import "./globals.css";
import { Poppins } from "next/font/google";

//font usage
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "500"],
  display: "swap",
});

//meta data
export const metadata = {
  title: "To do App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-neutral-800`}>{children}</body>
    </html>
  );
}
